CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title` varchar(500) NOT NULL,
	`excerpt` text,
	`content` text NOT NULL,
	`featuredImage` varchar(500),
	`category` enum('product','health','business','franchise','distributor','news','lifestyle') NOT NULL DEFAULT 'product',
	`metaTitle` varchar(255),
	`metaDescription` text,
	`keywords` text,
	`status` enum('draft','published','archived') NOT NULL DEFAULT 'draft',
	`author` varchar(255) DEFAULT 'NEON Team',
	`views` int DEFAULT 0,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
