CREATE TABLE `claimed_territories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`territoryLicenseId` int NOT NULL,
	`centerLat` decimal(10,7) NOT NULL,
	`centerLng` decimal(10,7) NOT NULL,
	`radiusMiles` int NOT NULL,
	`territoryName` varchar(255) NOT NULL,
	`zipCode` varchar(20),
	`city` varchar(100),
	`state` varchar(50),
	`status` enum('pending','active','expired') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp,
	CONSTRAINT `claimed_territories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `territory_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`currentStep` int NOT NULL DEFAULT 1,
	`centerLat` decimal(10,7),
	`centerLng` decimal(10,7),
	`radiusMiles` int,
	`territoryName` varchar(255),
	`estimatedPopulation` int,
	`termMonths` int,
	`totalCost` int,
	`firstName` varchar(100),
	`lastName` varchar(100),
	`email` varchar(320),
	`phone` varchar(50),
	`dateOfBirth` varchar(20),
	`streetAddress` varchar(255),
	`city` varchar(100),
	`state` varchar(50),
	`zipCode` varchar(20),
	`businessName` varchar(255),
	`businessType` enum('individual','llc','corporation','partnership'),
	`taxId` varchar(50),
	`yearsInBusiness` int,
	`investmentCapital` int,
	`franchiseExperience` text,
	`whyInterested` text,
	`agreedToTerms` int NOT NULL DEFAULT 0,
	`signature` varchar(255),
	`submittedAt` timestamp,
	`status` enum('draft','submitted','under_review','approved','rejected') NOT NULL DEFAULT 'draft',
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `territory_applications_id` PRIMARY KEY(`id`)
);
