CREATE TABLE `franchise_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`territoryCity` varchar(100) NOT NULL,
	`territoryState` varchar(100) NOT NULL,
	`territorySize` varchar(50) NOT NULL,
	`exclusivityType` varchar(50) NOT NULL,
	`investmentCapital` varchar(50) NOT NULL,
	`financingNeeded` varchar(50),
	`netWorth` varchar(50),
	`businessExperience` varchar(100) NOT NULL,
	`distributionExperience` text,
	`teamSize` varchar(50),
	`motivation` text NOT NULL,
	`timeline` varchar(50) NOT NULL,
	`questions` text,
	`status` enum('pending','under_review','approved','rejected') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `franchise_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `push_subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`endpoint` text NOT NULL,
	`p256dh` text NOT NULL,
	`auth` text NOT NULL,
	`userAgent` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `push_subscriptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vending_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`businessName` varchar(255),
	`businessType` varchar(100) NOT NULL,
	`yearsInBusiness` varchar(50),
	`city` varchar(100) NOT NULL,
	`state` varchar(100) NOT NULL,
	`zipCode` varchar(20) NOT NULL,
	`proposedLocations` text,
	`numberOfMachines` varchar(50) NOT NULL,
	`investmentBudget` varchar(50),
	`timeline` varchar(50),
	`experience` text,
	`questions` text,
	`status` enum('pending','under_review','approved','rejected') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `vending_applications_id` PRIMARY KEY(`id`)
);
