CREATE TABLE `vending_machine_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`machineModel` varchar(100) NOT NULL,
	`quantity` int NOT NULL DEFAULT 1,
	`totalPriceCents` int NOT NULL,
	`depositAmountCents` int NOT NULL,
	`paymentType` enum('full','deposit','payment_plan') NOT NULL,
	`paymentPlanMonths` int,
	`monthlyPaymentCents` int,
	`amountPaidCents` int NOT NULL DEFAULT 0,
	`remainingBalanceCents` int NOT NULL,
	`paymentsMade` int NOT NULL DEFAULT 0,
	`nextPaymentDue` timestamp,
	`stripeCustomerId` varchar(255),
	`stripeSubscriptionId` varchar(255),
	`stripePaymentIntentId` varchar(255),
	`status` enum('pending','deposit_paid','in_production','ready_for_delivery','delivered','cancelled','refunded') NOT NULL DEFAULT 'pending',
	`deliveryAddress` text,
	`deliveryCity` varchar(100),
	`deliveryState` varchar(100),
	`deliveryZip` varchar(20),
	`estimatedDelivery` timestamp,
	`installationDate` timestamp,
	`notes` text,
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vending_machine_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vending_payment_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int NOT NULL,
	`amountCents` int NOT NULL,
	`paymentType` enum('deposit','monthly','final','full') NOT NULL,
	`paymentNumber` int,
	`stripePaymentIntentId` varchar(255),
	`status` enum('pending','succeeded','failed','refunded') NOT NULL DEFAULT 'pending',
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `vending_payment_history_id` PRIMARY KEY(`id`)
);
