import { useState, useCallback, useMemo } from 'react';
import Tree from 'react-d3-tree';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  ChevronRight, 
  ChevronLeft, 
  Users, 
  DollarSign, 
  TrendingUp, 
  Award,
  Play,
  Pause,
  RotateCcw,
  Info,
  Zap
} from 'lucide-react';

// Tree node data structure for react-d3-tree
interface TreeNodeDatum {
  name: string;
  attributes?: Record<string, string>;
  children?: TreeNodeDatum[];
  nodeSvgShape?: {
    shape: string;
    shapeProps: Record<string, string | number>;
  };
}

// Tutorial step interface
interface TutorialStep {
  id: number;
  title: string;
  description: string;
  highlight: string[];
  treeData: TreeNodeDatum;
  tip: string;
}

// Custom node component for the tree
const CustomNode = ({ 
  nodeDatum, 
  toggleNode, 
  highlighted 
}: { 
  nodeDatum: TreeNodeDatum; 
  toggleNode: () => void;
  highlighted: boolean;
}) => {
  const isYou = nodeDatum.name === 'YOU';
  const rank = nodeDatum.attributes?.rank || 'Starter';
  
  const getRankColor = (rank: string) => {
    switch (rank.toLowerCase()) {
      case 'diamond': return '#b9f2ff';
      case 'ambassador': return '#ffd700';
      case 'platinum': return '#e5e4e2';
      case 'gold': return '#ffd700';
      case 'silver': return '#c0c0c0';
      case 'bronze': return '#cd7f32';
      default: return '#c8ff00';
    }
  };

  return (
    <g onClick={toggleNode} style={{ cursor: 'pointer' }}>
      {/* Glow effect for highlighted nodes */}
      {highlighted && (
        <circle
          r={35}
          fill="none"
          stroke="#c8ff00"
          strokeWidth={3}
          opacity={0.6}
          className="animate-pulse"
        />
      )}
      
      {/* Main node circle */}
      <circle
        r={isYou ? 30 : 25}
        fill={isYou ? '#c8ff00' : '#1a1a2e'}
        stroke={highlighted ? '#c8ff00' : getRankColor(rank)}
        strokeWidth={3}
      />
      
      {/* Node icon */}
      <text
        fill={isYou ? '#000' : '#fff'}
        fontSize={isYou ? 14 : 12}
        textAnchor="middle"
        dominantBaseline="middle"
        fontWeight="bold"
      >
        {isYou ? '⭐' : '👤'}
      </text>
      
      {/* Name label */}
      <text
        fill="#fff"
        fontSize={11}
        textAnchor="middle"
        y={45}
        fontWeight={isYou ? 'bold' : 'normal'}
      >
        {nodeDatum.name}
      </text>
      
      {/* Rank badge */}
      {nodeDatum.attributes?.rank && (
        <text
          fill={getRankColor(rank)}
          fontSize={9}
          textAnchor="middle"
          y={58}
        >
          {nodeDatum.attributes.rank}
        </text>
      )}
      
      {/* PV indicator */}
      {nodeDatum.attributes?.pv && (
        <text
          fill="#888"
          fontSize={8}
          textAnchor="middle"
          y={70}
        >
          {nodeDatum.attributes.pv} PV
        </text>
      )}
    </g>
  );
};

// Tutorial steps with progressive tree building
const tutorialSteps: TutorialStep[] = [
  {
    id: 1,
    title: "Welcome to Your Network",
    description: "As a NEON Energy distributor, you start at the top of your own binary tree. Your goal is to build two legs - a left leg and a right leg - by recruiting new distributors.",
    highlight: ['YOU'],
    treeData: {
      name: 'YOU',
      attributes: { rank: 'Starter', pv: '0' },
    },
    tip: "💡 You earn commissions based on the sales volume generated by your entire team!"
  },
  {
    id: 2,
    title: "Building Your First Leg",
    description: "When you recruit your first distributor, they're placed in your LEFT leg. This is your 'power leg' - focus on building depth here first.",
    highlight: ['Alex'],
    treeData: {
      name: 'YOU',
      attributes: { rank: 'Starter', pv: '100' },
      children: [
        {
          name: 'Alex',
          attributes: { rank: 'Starter', pv: '50' },
        }
      ]
    },
    tip: "💡 Your first recruit earns you a $50 Fast Start Bonus!"
  },
  {
    id: 3,
    title: "Balancing Your Tree",
    description: "Now add a distributor to your RIGHT leg. A balanced tree generates more commissions through the Binary Commission structure.",
    highlight: ['Jordan'],
    treeData: {
      name: 'YOU',
      attributes: { rank: 'Bronze', pv: '200' },
      children: [
        {
          name: 'Alex',
          attributes: { rank: 'Starter', pv: '50' },
        },
        {
          name: 'Jordan',
          attributes: { rank: 'Starter', pv: '50' },
        }
      ]
    },
    tip: "💡 Binary commissions pay 10% on your weaker leg's volume!"
  },
  {
    id: 4,
    title: "Depth Creates Leverage",
    description: "When Alex recruits Sam, your tree grows deeper. You earn commissions from ALL levels below you - this is the power of network marketing!",
    highlight: ['Sam'],
    treeData: {
      name: 'YOU',
      attributes: { rank: 'Bronze', pv: '300' },
      children: [
        {
          name: 'Alex',
          attributes: { rank: 'Starter', pv: '100' },
          children: [
            {
              name: 'Sam',
              attributes: { rank: 'Starter', pv: '50' },
            }
          ]
        },
        {
          name: 'Jordan',
          attributes: { rank: 'Starter', pv: '50' },
        }
      ]
    },
    tip: "💡 Matching Bonuses pay you a % of what your direct recruits earn!"
  },
  {
    id: 5,
    title: "Spillover Magic",
    description: "When you recruit more than 2 people, extras 'spill over' to help your team. Here, your 3rd recruit (Taylor) is placed under Alex, helping both of you!",
    highlight: ['Taylor'],
    treeData: {
      name: 'YOU',
      attributes: { rank: 'Silver', pv: '500' },
      children: [
        {
          name: 'Alex',
          attributes: { rank: 'Bronze', pv: '200' },
          children: [
            {
              name: 'Sam',
              attributes: { rank: 'Starter', pv: '50' },
            },
            {
              name: 'Taylor',
              attributes: { rank: 'Starter', pv: '50' },
            }
          ]
        },
        {
          name: 'Jordan',
          attributes: { rank: 'Starter', pv: '100' },
        }
      ]
    },
    tip: "💡 Spillover helps your team grow even when they're not actively recruiting!"
  },
  {
    id: 6,
    title: "Team Duplication",
    description: "Success comes from duplication. As your team members recruit their own people, your network grows exponentially!",
    highlight: ['Morgan', 'Casey'],
    treeData: {
      name: 'YOU',
      attributes: { rank: 'Gold', pv: '1000' },
      children: [
        {
          name: 'Alex',
          attributes: { rank: 'Silver', pv: '400' },
          children: [
            {
              name: 'Sam',
              attributes: { rank: 'Bronze', pv: '150' },
              children: [
                {
                  name: 'Morgan',
                  attributes: { rank: 'Starter', pv: '50' },
                }
              ]
            },
            {
              name: 'Taylor',
              attributes: { rank: 'Starter', pv: '100' },
            }
          ]
        },
        {
          name: 'Jordan',
          attributes: { rank: 'Bronze', pv: '200' },
          children: [
            {
              name: 'Casey',
              attributes: { rank: 'Starter', pv: '50' },
            }
          ]
        }
      ]
    },
    tip: "💡 Teach your team to duplicate your success - that's how leaders are built!"
  },
  {
    id: 7,
    title: "Rank Advancement",
    description: "As your team grows and generates volume, you advance through ranks: Starter → Bronze → Silver → Gold → Platinum → Diamond → Ambassador. Each rank unlocks higher commission percentages!",
    highlight: ['YOU', 'Alex'],
    treeData: {
      name: 'YOU',
      attributes: { rank: 'Platinum', pv: '2500' },
      children: [
        {
          name: 'Alex',
          attributes: { rank: 'Gold', pv: '800' },
          children: [
            {
              name: 'Sam',
              attributes: { rank: 'Silver', pv: '300' },
              children: [
                {
                  name: 'Morgan',
                  attributes: { rank: 'Bronze', pv: '150' },
                  children: [
                    {
                      name: 'Riley',
                      attributes: { rank: 'Starter', pv: '50' },
                    }
                  ]
                }
              ]
            },
            {
              name: 'Taylor',
              attributes: { rank: 'Bronze', pv: '200' },
            }
          ]
        },
        {
          name: 'Jordan',
          attributes: { rank: 'Silver', pv: '400' },
          children: [
            {
              name: 'Casey',
              attributes: { rank: 'Bronze', pv: '150' },
            },
            {
              name: 'Drew',
              attributes: { rank: 'Starter', pv: '100' },
            }
          ]
        }
      ]
    },
    tip: "💡 Platinum rank unlocks the Leadership Pool - share in company-wide profits!"
  },
  {
    id: 8,
    title: "Your Empire Awaits",
    description: "This is just the beginning! With dedication and the right strategy, your network can grow to hundreds or thousands of distributors, generating passive income for years to come.",
    highlight: ['YOU'],
    treeData: {
      name: 'YOU',
      attributes: { rank: 'Diamond', pv: '10000' },
      children: [
        {
          name: 'Alex',
          attributes: { rank: 'Platinum', pv: '3000' },
          children: [
            {
              name: 'Sam',
              attributes: { rank: 'Gold', pv: '1000' },
              children: [
                {
                  name: 'Morgan',
                  attributes: { rank: 'Silver', pv: '400' },
                },
                {
                  name: 'Avery',
                  attributes: { rank: 'Bronze', pv: '200' },
                }
              ]
            },
            {
              name: 'Taylor',
              attributes: { rank: 'Silver', pv: '500' },
              children: [
                {
                  name: 'Quinn',
                  attributes: { rank: 'Bronze', pv: '150' },
                }
              ]
            }
          ]
        },
        {
          name: 'Jordan',
          attributes: { rank: 'Gold', pv: '2000' },
          children: [
            {
              name: 'Casey',
              attributes: { rank: 'Silver', pv: '600' },
              children: [
                {
                  name: 'Blake',
                  attributes: { rank: 'Bronze', pv: '200' },
                }
              ]
            },
            {
              name: 'Drew',
              attributes: { rank: 'Silver', pv: '400' },
            }
          ]
        }
      ]
    },
    tip: "🚀 Ready to start? Go to the Join page and become a NEON distributor today!"
  }
];

export function GenealogyTreeTutorial() {
  const [currentStep, setCurrentStep] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [translate, setTranslate] = useState({ x: 300, y: 80 });

  const step = tutorialSteps[currentStep];

  // Auto-play functionality
  const handleAutoPlay = useCallback(() => {
    if (isPlaying) {
      setIsPlaying(false);
      return;
    }
    
    setIsPlaying(true);
    const interval = setInterval(() => {
      setCurrentStep(prev => {
        if (prev >= tutorialSteps.length - 1) {
          setIsPlaying(false);
          clearInterval(interval);
          return prev;
        }
        return prev + 1;
      });
    }, 4000);

    return () => clearInterval(interval);
  }, [isPlaying]);

  const handleNext = () => {
    if (currentStep < tutorialSteps.length - 1) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handlePrev = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
    }
  };

  const handleReset = () => {
    setCurrentStep(0);
    setIsPlaying(false);
  };

  // Custom render function for nodes
  const renderCustomNode = useCallback(({ nodeDatum, toggleNode }: any) => (
    <CustomNode 
      nodeDatum={nodeDatum} 
      toggleNode={toggleNode}
      highlighted={step.highlight.includes(nodeDatum.name)}
    />
  ), [step.highlight]);

  // Memoize tree container dimensions
  const containerRef = useCallback((containerElem: HTMLDivElement | null) => {
    if (containerElem) {
      const { width } = containerElem.getBoundingClientRect();
      setTranslate({ x: width / 2, y: 80 });
    }
  }, []);

  return (
    <div className="w-full max-w-6xl mx-auto p-4 space-y-6">
      {/* Header */}
      <div className="text-center space-y-2">
        <h1 className="text-3xl font-bold text-white flex items-center justify-center gap-2">
          <Zap className="w-8 h-8 text-[#c8ff00]" />
          Binary Tree Tutorial
          <Zap className="w-8 h-8 text-[#c8ff00]" />
        </h1>
        <p className="text-gray-400">
          Learn how the NEON Energy MLM compensation plan works
        </p>
      </div>

      {/* Progress bar */}
      <div className="relative">
        <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
          <div 
            className="h-full bg-gradient-to-r from-[#c8ff00] to-[#00ff88] transition-all duration-500"
            style={{ width: `${((currentStep + 1) / tutorialSteps.length) * 100}%` }}
          />
        </div>
        <div className="flex justify-between mt-1 text-xs text-gray-500">
          <span>Step {currentStep + 1} of {tutorialSteps.length}</span>
          <span>{Math.round(((currentStep + 1) / tutorialSteps.length) * 100)}% Complete</span>
        </div>
      </div>

      {/* Main content grid */}
      <div className="grid lg:grid-cols-2 gap-6">
        {/* Tree visualization */}
        <Card className="bg-gray-900/50 border-gray-800">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg flex items-center gap-2">
              <Users className="w-5 h-5 text-[#c8ff00]" />
              Your Network Tree
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div 
              ref={containerRef}
              className="h-[400px] bg-gray-950 rounded-lg overflow-hidden"
            >
              <Tree
                data={step.treeData}
                orientation="vertical"
                translate={translate}
                nodeSize={{ x: 120, y: 100 }}
                separation={{ siblings: 1.5, nonSiblings: 2 }}
                pathFunc="step"
                renderCustomNodeElement={renderCustomNode}
                pathClassFunc={() => 'stroke-[#c8ff00] stroke-2 fill-none opacity-50'}
                zoom={0.8}
                enableLegacyTransitions
                transitionDuration={500}
              />
            </div>
          </CardContent>
        </Card>

        {/* Tutorial content */}
        <div className="space-y-4">
          <Card className="bg-gray-900/50 border-gray-800">
            <CardHeader>
              <div className="flex items-center justify-between">
                <Badge variant="outline" className="text-[#c8ff00] border-[#c8ff00]">
                  Step {step.id}
                </Badge>
                <div className="flex gap-2">
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={handleReset}
                    className="text-gray-400 hover:text-white"
                  >
                    <RotateCcw className="w-4 h-4" />
                  </Button>
                  <Button
                    size="sm"
                    variant={isPlaying ? "default" : "outline"}
                    onClick={handleAutoPlay}
                    className={isPlaying ? "bg-[#c8ff00] text-black" : ""}
                  >
                    {isPlaying ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}
                    <span className="ml-1">{isPlaying ? 'Pause' : 'Auto'}</span>
                  </Button>
                </div>
              </div>
              <CardTitle className="text-xl text-white mt-2">{step.title}</CardTitle>
              <CardDescription className="text-gray-300 text-base leading-relaxed">
                {step.description}
              </CardDescription>
            </CardHeader>
            <CardContent>
              {/* Tip box */}
              <div className="bg-[#c8ff00]/10 border border-[#c8ff00]/30 rounded-lg p-4 flex items-start gap-3">
                <Info className="w-5 h-5 text-[#c8ff00] flex-shrink-0 mt-0.5" />
                <p className="text-sm text-gray-300">{step.tip}</p>
              </div>
            </CardContent>
          </Card>

          {/* Stats cards */}
          <div className="grid grid-cols-3 gap-3">
            <Card className="bg-gray-900/50 border-gray-800 p-4">
              <div className="flex flex-col items-center text-center">
                <Users className="w-6 h-6 text-[#c8ff00] mb-1" />
                <span className="text-2xl font-bold text-white">
                  {countNodes(step.treeData)}
                </span>
                <span className="text-xs text-gray-400">Team Size</span>
              </div>
            </Card>
            <Card className="bg-gray-900/50 border-gray-800 p-4">
              <div className="flex flex-col items-center text-center">
                <TrendingUp className="w-6 h-6 text-green-400 mb-1" />
                <span className="text-2xl font-bold text-white">
                  {step.treeData.attributes?.pv || 0}
                </span>
                <span className="text-xs text-gray-400">Total PV</span>
              </div>
            </Card>
            <Card className="bg-gray-900/50 border-gray-800 p-4">
              <div className="flex flex-col items-center text-center">
                <Award className="w-6 h-6 text-yellow-400 mb-1" />
                <span className="text-lg font-bold text-white">
                  {step.treeData.attributes?.rank || 'Starter'}
                </span>
                <span className="text-xs text-gray-400">Your Rank</span>
              </div>
            </Card>
          </div>

          {/* Navigation buttons */}
          <div className="flex justify-between gap-4">
            <Button
              variant="outline"
              onClick={handlePrev}
              disabled={currentStep === 0}
              className="flex-1"
            >
              <ChevronLeft className="w-4 h-4 mr-1" />
              Previous
            </Button>
            <Button
              onClick={handleNext}
              disabled={currentStep === tutorialSteps.length - 1}
              className="flex-1 bg-[#c8ff00] text-black hover:bg-[#b8ef00]"
            >
              Next
              <ChevronRight className="w-4 h-4 ml-1" />
            </Button>
          </div>
        </div>
      </div>

      {/* Commission breakdown */}
      <Card className="bg-gray-900/50 border-gray-800">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <DollarSign className="w-5 h-5 text-[#c8ff00]" />
            Commission Structure
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid md:grid-cols-4 gap-4">
            <div className="bg-gray-800/50 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-[#c8ff00]">$50</div>
              <div className="text-sm text-gray-400">Fast Start Bonus</div>
              <div className="text-xs text-gray-500 mt-1">Per direct recruit</div>
            </div>
            <div className="bg-gray-800/50 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-green-400">10%</div>
              <div className="text-sm text-gray-400">Binary Commission</div>
              <div className="text-xs text-gray-500 mt-1">On weaker leg volume</div>
            </div>
            <div className="bg-gray-800/50 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-blue-400">5-20%</div>
              <div className="text-sm text-gray-400">Matching Bonus</div>
              <div className="text-xs text-gray-500 mt-1">On direct recruit earnings</div>
            </div>
            <div className="bg-gray-800/50 rounded-lg p-4 text-center">
              <div className="text-2xl font-bold text-purple-400">2%</div>
              <div className="text-sm text-gray-400">Leadership Pool</div>
              <div className="text-xs text-gray-500 mt-1">Platinum+ ranks</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// Helper function to count nodes in tree
function countNodes(node: TreeNodeDatum): number {
  let count = 1;
  if (node.children) {
    for (const child of node.children) {
      count += countNodes(child);
    }
  }
  return count;
}

export default GenealogyTreeTutorial;
